CREATE TABLE users(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	name TEXT NOT NULL,
	surname TEXT NOT NULL,
	login TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	status TEXT NOT NULL,
	group_id INTEGER,
	experience TEXT);

CREATE TABLE crowdfunds(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	name TEXT NOT NULL,
	total_price INTEGER NOT NULL,
	current_price INTEGER NOT NULL,
	founder_id Integer NOT NULL);

CREATE TABLE artifacts(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	name TEXT NOT NULL UNIQUE,
	price INTEGER NOT NULL,
	category TEXT);

CREATE TABLE quests(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	name TEXT NOT NULL UNIQUE,
	reward INTEGER NOT NULL,
	category TEXT);

CREATE TABLE wallet(
	current_balance INTEGER NOT NULL,
	total_income INTEGER  NOT NULL,
	student_id INTEGER NOT NULL UNIQUE, 
			   FOREIGN KEY (student_id) REFERENCES users(id));

CREATE TABLE student_quests(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	quests_id INTEGER NOT NULL,
	student_id INTEGER NOT NULL,
	status TEXT);

CREATE TABLE groups(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	name TEXT NOT NULL UNIQUE);

CREATE TABLE student_artifacts(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	artifact_id INTEGER NOT NULL,
	student_id INTEGER NOT NULL,
	status TEXT NOT NULL);

CREATE TABLE experience_levels(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	name TEXT NOT NULL UNIQUE,
	money_required INTEGER NOT NULL);

CREATE TABLE category(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	name TEXT NOT NULL UNIQUE);
)
